### ISSUE TITLE
게시글 이미지 업로드 시 개수 제한 팝업 뜨지만 그대로 올라가는 현상

### ISSUE THREAD

**Issue by donkeeman** [FEeasy404/GameUs#117]
## 수정 사항 설명
게시글에 이미지를 올릴 때 3개까지 가능하다는 alert 창이 뜨지만 실제로는 3개 이상 업로드가 가능합니다. alert 창을 아예 없애도 괜찮을 거 같아요!

## 할 일
- [ ] alert 창 없애기

**Comment by boram2445** [comment]
헉.. 3개까지만 업로드 가능하게 했었는데 리팩토링하면서 이상해졌나봐요ㅠㅠ 수정해 보겠습니다
