### ISSUE TITLE
스크롤시 헤더 배경에 일부 요소들이 투과됨

### ISSUE THREAD

**Issue by yeodahui** [FEeasy404/GameUs#127]
## 버그 발생 설명
페이지에서 스크롤 시 일부 요소들이 배경에 투과되는 현상이 있습니다.

### 홈피드 페이지
![헤더 배경 투과](https://user-images.githubusercontent.com/102221305/180705087-67bdbced-e9f3-44fc-bf95-85f1eefe5348.gif)

### 팔로잉 페이지
![헤더 배경 투과2](https://user-images.githubusercontent.com/102221305/180705180-b50d9f05-eae4-4098-a751-5386da575221.gif)

## 할 일
- [ ] 헤더 배경 확인

**Comment by boram2445** [comment]
오....? 왜저랩... 감사합니다 다히님 확인해보겠습니다😂
