### ISSUE TITLE
각 section의 h1 태그를 h2로 수정하기

### ISSUE THREAD

**Issue by donkeeman** [FEeasy404/GameUs#140]
## 수정 사항 설명
- section마다 주었던 `<h1>` 태그를 spa이므로 `<h2>`로 수정해야 합니다. 

## 할 일
- [ ] `<h1>`을 `<h2>`로 수정하기

## ETC
페이지에 단 하나의 h1이 있어야 한다고 하는데, index.js나 App.jsx에서 h1을 따로 주는 게 맞을까요?

**Comment by yeodahui** [comment]
넵 App.js에서 주는 게 좋을 것 같습니당 ㅠㅠ

**Comment by yeodahui** [comment]
이 부분 제가 수정하겠습니다!
