### ISSUE TITLE
하단탭 화면 좁아질 경우 height가 높아짐

### ISSUE THREAD

**Issue by boram2445** [FEeasy404/GameUs#147]
## 버그 발생 설명

- 화면이 좁아질 경우 하단탭의 height가 높아져 페이지 하단 내용을 가립니다! 
- 게시물수정' 텍스트가 화면이 좁아져도 한줄로 유지되도록 하면 좋을것 같습니다!
![image](https://user-images.githubusercontent.com/68495264/181241976-fd359045-71f2-43c4-9c3b-99efd66a1661.png)

## 할 일
- [ ] 하단탭 height 수정

**Comment by yeodahui** [comment]
넵! 수정해보겠습니다~
