### ISSUE TITLE
PostCard 프로필 사진 링크 범위

### ISSUE THREAD

**Issue by boram2445** [FEeasy404/GameUs#159]
## 버그 발생 설명

- PostCard 컴포넌트에서 링크 클릭 범위가 프로필 사진 보다 밑으로 길어져서 파란 범위를 클릭하면 링크로 연결된곳으로 이동합니다! 

![image](https://user-images.githubusercontent.com/68495264/181401304-0d20256a-c8fd-4fc4-ab12-eb958d2c10f9.png)

## 할 일
- [x] 링크 범위 프로필 사진으로 축소

**Comment by yeodahui** [comment]
앗 이건 생각 못했네... 수정할게요!
