### ISSUE TITLE
잘못된 경로의 이미지들 대체 이미지로 교체하거나 예외처리 필요

### ISSUE THREAD

**Issue by boram2445** [FEeasy404/GameUs#166]
## 버그 발생 설명

잘못된 이미지 경로를 가지고 있는 유저들의 
이미지들을 대체 이미지로 바꾸거나, 예외처리를 해주어야 할 것 같습니다. 
(이미지 경로 처리 방법이 다른 팀들이 있는듯 합니다...🤔)

![image](https://user-images.githubusercontent.com/68495264/181441431-0dc3c023-9fbe-4a46-80a4-0bf77c4e6544.png)

![image](https://user-images.githubusercontent.com/68495264/181441533-5f7e5b8a-9f3a-408a-8c02-b8d4b383acae.png)

## 할 일
- [ ] 대체 이미지 결정
- [ ] 잘못된 이미지 경로 판별 (예외처리)

**Comment by donkeeman** [comment]
이미지 문자열에 mandarin 어쩌고 주소가 포함되어있는지 검사하면 될거같습니다!
