### ISSUE TITLE
너무 긴 댓글의 줄바꿈 필요

### ISSUE THREAD

**Issue by donkeeman** [FEeasy404/GameUs#167]
## 버그 발생 설명
댓글 컴포넌트에도 max-width를 설정해서 줄바꿈을 해줘야 할거 같습니다...
![image](https://user-images.githubusercontent.com/79434205/181448289-8189f2ab-87d4-406b-858c-7a1b9a7507ac.png)

## 할 일
- [x] 댓글 줄바꿈 처리

**Comment by boram2445** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ넵......
