### ISSUE TITLE
버튼 안의 텍스트에 폰트 미적용

### ISSUE THREAD

**Issue by donkeeman** [FEeasy404/GameUs#168]
## 수정 사항 설명
- 버튼 안의 텍스트에 폰트가 적용되지 않고 있는 거 같아요! 제가 건드려보려고 했는데 잘 모르겠어서 이슈로 올립니다 😅 
![image](https://user-images.githubusercontent.com/79434205/181491130-7df1f9c1-d750-40c3-8fa0-90175fd4c72b.png)

## 할 일
- [x] 버튼 텍스트에 폰트 적용하기

**Comment by boram2445** [comment]
저도 어떻게 수정해야 하는지 몰라서 나뒀는데, input value 폰트도 부탁드립니다!

**Comment by yeodahui** [comment]
아놔 이거 왜이래
넵 적용해보겠습니다~~

**Comment by donkeeman** [comment]
351e918f2b6cf241b5e3f7f3074b196865989d85 에서 해결했습니다!
