### ISSUE TITLE
프로필 소개 글자수 제한 및 줄임말

### ISSUE THREAD

**Issue by boram2445** [FEeasy404/GameUs#180]
## 버그 발생 설명

- 돌아다니다가 발견했습니다..! 프로필 소개 글자수 제한 및 줄임말 설정이 필요할 것 같아요🤣
![2022-07-30 22;25;21](https://user-images.githubusercontent.com/68495264/181916458-788ad3fb-a546-436d-ab52-e4ada6f4c3fd.gif)

## 할 일
- [x] 프로필 소개 줄임말 설정 
- [x] 프로필 설정시 소개 글자수 제한

**Comment by donkeeman** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 수정해보겠습니다
