### ISSUE TITLE
판매 상품 등록 페이지에서 사진 업로드 시 가로 여백이 남는 현상

### ISSUE THREAD

**Issue by yeodahui** [FEeasy404/GameUs#61]
## 수정 사항 설명
![image](https://user-images.githubusercontent.com/102221305/178971766-2a4a475e-5530-4c3f-b377-47c990d9f4cb.png)
상품 등록 페이지에서 사진을 업로드 할 때, 비율이 맞지 않으면 사진 영역이 꽉 차지 않고 여백이 남습니다.

## 할 일
- [ ] img 태그의 사이즈 조정

**Comment by donkeeman** [comment]
아 이거 만약 세로로만 긴 이미지라면 너비만 100%를 주고 사진의 가운데를 보여주고 위, 아래는 잘라버리는 게 맞는지, 아니면 원본 비율을 무시하고 억지로 너비를 늘려서 꽉 채워야 하는지 이런 게 애매해서
저는 이미지 원본 비율을 훼손하지 않고 전체를 보여주는 게 맞다고 판단하여 우선은 `max-width: 100%`, `max-height: 100%`를 둘 다 설정해놔서 그렇습니다...!
이거 얘기 나눠보면 좋을 거 같습니다! 아니면 이미지별로 설정을 다르게 해도 괜찮을 거 같고요.
