### ISSUE TITLE
프로필 페이지 버튼 줄어듬

### ISSUE THREAD

**Issue by yeodahui** [FEeasy404/GameUs#91]
## 수정 사항 설명
사용자 프로필 페이지를 모바일처럼 좁은 너비 화면에서 봤을 때 프로필 수정 버튼과 상품 등록 버튼이 애매하게 줄어듭니다!
![image](https://user-images.githubusercontent.com/102221305/179937819-f105d60d-27ed-4b51-9404-c29e9644f8e7.png)

## 할 일
- [x] 버튼 콘텐츠 줄바꿈 비활성화

**Comment by donkeeman** [comment]
![image](https://user-images.githubusercontent.com/79434205/179964644-cf5da84c-3c04-4213-b4b3-f3345ee388d6.png)
제 화면에서는 잘 보여서 괜찮은 줄 알았어요.. 수정해보겠습니다..

**Comment by yeodahui** [comment]
수정된 것 테스트 확인 완료~
![image](https://user-images.githubusercontent.com/102221305/180704785-567c0628-f8c1-4610-9b8f-9a78b7345b2f.png)
