### ISSUE TITLE
프로필 수정 페이지에 여백 없음

### ISSUE THREAD

**Issue by yeodahui** [FEeasy404/GameUs#93]
## 수정 사항 설명
![image](https://user-images.githubusercontent.com/102221305/179940667-2922d3f5-2454-41b9-b9ae-45fa129210e3.png)
프로필 수정 페이지가 유독 여백이 없네요! 추가해주면 좋을 것 같습니다.

## 할 일
- [x] 여백 추가

**Comment by donkeeman** [comment]
지금은 제가 회원가입 페이지를 건들면서 폼이 고장났습니다 😢 프로필 수정 기능 넣으면서 css도 수정하겠습니다!

**Comment by yeodahui** [comment]
여백 정상적으로 들어가는 것 확인했습니다!

갤럭시 S8
![image](https://user-images.githubusercontent.com/102221305/180704445-b2023033-31c6-400c-abd5-efebb84de8c5.png)

아이패트 Mini
![image](https://user-images.githubusercontent.com/102221305/180704499-25f834ba-95ed-4980-ab3b-9d2ee8a66152.png)
