### ISSUE TITLE
게시글 업로드 페이지의 사진 추가 버튼이 고정되지 않음

### ISSUE THREAD

**Issue by yeodahui** [FEeasy404/GameUs#99]
## 수정 사항 설명
![게시글 업로드 페이지](https://user-images.githubusercontent.com/102221305/180136595-d34ff3be-899d-4fc8-b3a8-930f39540caa.gif)

게시글 업로드 페이지에 들어가면 스크롤이 생겨 사진 추가 버튼이 스크롤을 내려야만 보이는 문제가 있습니다!

## 할 일
- [ ] 버튼의 위치를 position: absolute가 아닌 fixed로 수정

**Comment by boram2445** [comment]
https://github.com/FEeasy404/GameUs/pull/97 
지난 pr에서 수정했습니다!! pull 하고 확인 부탁드립니다 :>

**Comment by yeodahui** [comment]
> #97 지난 pr에서 수정했습니다!! pull 하고 확인 부탁드립니다 :>

아하 pull 되기 전이라 이렇게 보였나봐요 ㅎㅎ 알겠습니다 이슈 닫겠습니당
